### ISSUE TITLE
Automate and GMCM

### ISSUE THREAD

**Issue by welterusten** [justastranger/ArtisanProductsCopyQuality#1]
Running the Mod alongside Automate and GMCM causes the mod to not function/ revert to vanilla behaviour.

Log: https://smapi.io/log/c55aa89fc8fe4a6b8cde8b704c006033

**Comment by justastranger** [comment]
This shouldn't be possible unless the config is somehow corrupted or not loaded in time. Regardless, should be fixed in [a6da48e](https://github.com/justastranger/ArtisanProductsCopyQuality/commit/a6da48ed01880fa8c9cb22e81f807d5c13882064) with [release 1.1.1](https://github.com/justastranger/ArtisanProductsCopyQuality/releases/tag/1.1.1).
